### ISSUE TITLE
Remove load.project() function from every script in src

### ISSUE THREAD

**Issue by mberrien-fitzsimons** [kippchicago/Illuminate-Report-Cards#4]
https://github.com/kippchicago/Illuminate-Report-Cards/blob/c398f15cf5d334a7d9bd96155fa502c55a86af2b/src/Attendance.R#L2-L3

How to re-organize src folder so that each script doesn't call `load.project()` when it runs. This loads libraries and re-downloads database files each time.

**Comment by chrishaid** [comment]
Solution is to comment out `library(ProjectTemplate)` and `load.project()` from the scripts that are being sourced (other users can just remove comments if they want to run a file solo)
