### ISSUE TITLE
Replace magic numbers

### ISSUE THREAD

**Issue by mberrien-fitzsimons** [kippchicago/Illuminate-Report-Cards#6]
https://github.com/kippchicago/Illuminate-Report-Cards/blob/c398f15cf5d334a7d9bd96155fa502c55a86af2b/munge/02-grades_munge.R#L12

**Comment by chrishaid** [comment]
https://www.tidyverse.org/blog/2020/02/glue-strings-and-tidy-eval/

**Comment by chrishaid** [comment]
That link shows some new functionality for programming with tidy eval which allows "variable tunnelling" and assign programatically-generated variables on either side fo an equals sign ( = 
) by using these walrus equals sings ( := )
